### ISSUE TITLE
TypeError: Cannot read property 'sigBytes' of undefined

### ISSUE THREAD

**Issue by rebornishard** [tpenaranda/vue-cryptojs#1]
TypeError: Cannot read property 'sigBytes' of undefined

this is what i get for testing it

at least give dummy signature for it

Vue.CryptoJS.HmacSHA1('Signature','Message')

this.CryptoJS.HmacSHA1('Signature','Message')

this.$CryptoJS.HmacSHA1('Signature','Message')

**Comment by tpenaranda** [comment]
Solved by https://github.com/tpenaranda/vue-cryptojs/pull/2
