### ISSUE TITLE
Doesn't work with Vue2

### ISSUE THREAD

**Issue by scorpioRedRoyal** [tpenaranda/vue-cryptojs#22]
Hi!
I have installed this module by
 `npm install vue-cryptojs`

Then in **main.js**

```
import VueCryptojs from 'vue-cryptojs'

new Vue({
  router,
  store,
  VueCryptojs,
  render: h => h(App)
}).$mount('#app')
```

But when I try to use it on my component

`const encryptedText = this.$CryptoJS.AES.encrypt("Hi There!", "Secret Passphrase").toString()`

Got an error:

"TypeError: Cannot read properties of undefined (reading 'AES')"

I have try to print **this.$CryptoJS** the result is **undefined**

What is wrong?

**Comment by tpenaranda** [comment]
@scorpioRedRoyal 

```
// Vue2
import Vue from 'vue'
import VueCryptojs from 'vue-cryptojs'

Vue.use(VueCryptojs)
```

Give a try to Vue.use()

**Comment by scorpioRedRoyal** [comment]
> @scorpioRedRoyal
> 
> ```
> // Vue2
> import Vue from 'vue'
> import VueCryptojs from 'vue-cryptojs'
> 
> Vue.use(VueCryptojs)
> ```
> 
> Give a try to Vue.use()

Where I have to try Vue.use() in main.j or in component?

**Comment by scorpioRedRoyal** [comment]
> @scorpioRedRoyal
> 
> ```
> // Vue2
> import Vue from 'vue'
> import VueCryptojs from 'vue-cryptojs'
> 
> Vue.use(VueCryptojs)
> ```
> 
> Give a try to Vue.use()

Thanks! It's working

**Comment by scorpioRedRoyal** [comment]
Is it possible to use this module, not in the component?
I mean, I have a js file where is HTTP request logic, and I want to invoke VueCrypto there, but unsuccessful

**Comment by tpenaranda** [comment]
No component? No vue?

`import cryptojs from 'crypto-js'`


@scorpioRedRoyal
