### ISSUE TITLE
can it run using window ?

### ISSUE THREAD

**Issue by rebornishard** [tpenaranda/vue-cryptojs#3]
i wanted to load this in main.js
and call this one with window, can this one do that ?
thanks

**Comment by tpenaranda** [comment]
@rebornishard This package is for binding CryptoJS to Vue instance.
If you want CryptoJS in the global window object you can do:
```
window.CryptoJS = require("crypto-js");
console.log(window.CryptoJS.HmacSHA1("Message", "Key"));
```

**Comment by rebornishard** [comment]
@tpenaranda thanks a lot,
what i do for now is import cryptojs in frontend
and using Vue-crypto behind the light

thanks for a guiding light

**Comment by tpenaranda** [comment]
Also, something else you can do @rebornishard  (I don't suggest this practice but maybe it can work for you) is attach the Vue instance to window object when creating the VueJS app
```
window.vm = new Vue({<options>}).$mount('<element id>')
```
And later... get the vue-cryptojs instance by doing
```
window.vm.CryptoJS
```
