### ISSUE TITLE
How do i decrypt with this.

### ISSUE THREAD

**Issue by otorrinolaringologista** [tpenaranda/vue-cryptojs#4]
I used the following to encrypt and decrypt functions according to the Crypto-js documentation but i get an error

> let ciphertext = this.CryptoJS.SHA1('Message', 'Key')
> let decryption = this.CryptoJS.SHA1.decrypt(ciphertext, 'Key')

error: this.CryptoJS.SHA1.decrypt is not a function"

i can encrypt just fine but i can't decrypt.

**Comment by tpenaranda** [comment]
Hi @otorrinolaringologista,  since SHA1 output is a message digest there is no "decrypt" function.
My bet is you want simple text encrypt/decrypt solution let me show you how to do that:

```
    const ciphertext = this.CryptoJS.AES.encrypt("Hi There!", "Secret Passphrase").toString()
    const decryption = this.CryptoJS.AES.decrypt(ciphertext, "Secret Passphrase").toString(this.CryptoJS.enc.Utf8)
```

Let me know any questions, happy coding!
