### ISSUE TITLE
how to use with vue 3

### ISSUE THREAD

**Issue by mrushdi81** [tpenaranda/vue-cryptojs#9]
How to use it with Vue3

**Comment by MicaelaGuimaraes** [comment]
@mrushdi81 were you able to use npm in your project?

**Comment by matteusbatterie** [comment]
@mrushdi81 I still couldn't figure out how to use `vue-cryptojs` specifically but I managed to solve my problem by implementing an util class and import regular [CryptoJS](https://www.npmjs.com/package/crypto-js) in it. This class would function merely as a facade to Crypto's cryptography methods, that way I can import my class within my components with ease.

**Comment by tpenaranda** [comment]
hey @mrushdi81 @matteusbatterie thanks for your input! currently vue-cryptojs doesn't support Vue3 but I'm working right now in order to add support, I'll keep you posted, thanks!

**Comment by tpenaranda** [comment]
@mrushdi81 @matteusbatterie Issue solved on https://github.com/tpenaranda/vue-cryptojs/releases/tag/v2.2.0 version.
npm package https://www.npmjs.com/package/vue-cryptojs and readme file updated with Vue3 install procedure. Thanks!

**Comment by matteusbatterie** [comment]
Cheers! I'm very fond that you replied and solved it with such agility, great job!

I retried and implemented it again on my component and it works just fine. 

_PS: Just a little of feedback, including in the Vue3 usage example how to use the cryptojs wouldn't hurt :p, although it is implied that you can use the same way you do with Vue2 but replacing the `this.$CryptoJS` instance._ Other than that, amazing work, thanks!
